DISCORD_TOKEN="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
SPOTIFY_USERNAME="foobar@gmail.com"
SPOTIFY_PASSWORD="my password"
DISCORD_USER_ID=111111111111111111
GUILD_ID=1111111111111111111
